### ISSUE TITLE
Unable to load/allocate model with TFLite API

### ISSUE THREAD

**Issue by smertrios** [google-coral/project-posenet#11]
Hi, if possible, what is needed to be able to load one of the models using the TFLite API?

 If not, what are the differences with TFLite vs. Edget-TPU API when dealing with CustomOP? Where do those resides for this project?

```
interpreter = Interpreter(
    model_path='models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite',
    experimental_delegates=[load_delegate('libedgetpu.so.1.0')]
   )
interpreter.allocate_tensors() # => RunTime Error
```

=> _Encountered unresolved custom op: **PosenetDecoderOp**.Node number 1_

Thank you.

**Comment by mtyka** [comment]
The custom Op is implemented in our API. It is not currently possible to run these posenet models using the normal tflite API, only using our API. We're working on getting that supported soon.
