### ISSUE TITLE
about the fps on raspberry pi

### ISSUE THREAD

**Issue by willfu** [google-coral/project-posenet#14]
@mtyka thanks for the work. I am curious about the frame rate on raspberry pi. do you have any data for that?

**Comment by JimWest** [comment]
I've tried it, Raspberry PI 4 with Intel Realsense, set to 640 x 480 and 60 FPS output (image not resized for network):

posenet_mobilenet_v1_075_721_1281 : ~8 FPS 
posenet_mobilenet_v1_075_481_641: ~ 15 FPS
posenet_mobilenet_v1_075_353_481:~ 30 FPS

**Comment by willfu** [comment]
thanks @JimWest
