### ISSUE TITLE
Direct pose

### ISSUE THREAD

**Issue by bhack** [google-coral/project-posenet#16]
What do you think about anchor-free inspired approaches like https://arxiv.org/abs/1911.07451?
Are these model plausible for Coral devices?
Do you plan to have an example here?

If you can talk internally with other TF teams see also HUB:
https://github.com/tensorflow/hub/issues/424

And related:
https://github.com/tensorflow/models/issues/4676

**Comment by mtyka** [comment]
Hi,

This seems certainly an interesting approach though i'm not deeply familiar with it. The convolutional parts of this would likely run on EdgeTPU no problem. 
The post processing will have to get done on CPU i suspect. 
We don't currently plan to provide such models as pretrained/canned examples.
