### ISSUE TITLE
Request Posenet *.tflite file (not compilied with edge_tpu_compiler yet)

### ISSUE THREAD

**Issue by AlexTraan** [google-coral/project-posenet#19]
Hi Team,
Currently, this repository only contained *_edgetpu.tflite file for posenet. I would like to request *.tflite file (not compilied with edge_tpu_compiler yet) for co-compile 2 model purpose.

Can you please help me?

**Comment by mtyka** [comment]
Done.

**Comment by AlexTraan** [comment]
Hi Mtyka,

I cannot compile (with edge tpu compiler) successfull for your uploaded *.tflite file. The error happen "Edge TPU Compiler version 2.0.267685300
ERROR: Encountered unresolved custom op: PosenetDecoderOp.
ERROR: Node number 32 (PosenetDecoderOp) failed to prepare.
"
Do I need any specific parameter when run edge_tpu_compiler?

Many thank

**Comment by mtyka** [comment]
Hmm, yeah, unfortunately what you are trying todo may not be possible, or at least be a bit tricky right now. PoseNet requires a custom op at the end and the compiler won't compile graphs with custom ops. 
The only way currently is to manually cut the graph (using toco), compile, and then stitch it back together (using this tool: https://github.com/google-coral/edgetpu/blob/master/src/cpp/tools/join_tflite_models.cc).
In theory this would work with co-compilation but i've never tried it.

**Comment by AlexTraan** [comment]
Hi mtyka,

Thank you for your reply.

"In theory this would work with co-compilation but i've never tried it."
>> i would like to try it. Can you help me?

"The only way currently is to manually cut the graph (using toco), compile, and then stitch it back together (using this tool: https://github.com/google-coral/edgetpu/blob/master/src/cpp/tools/join_tflite_models.cc)."
>> for first step ("manually cut the graph (using toco)"), i need *.pb file for do this, can you support me?

Thank you

**Comment by AlexTraan** [comment]
Hi mtyka,

For co-compilation Posenet purpose, i would like to confirm the flow:
1> manually cut the graph -> output: tflite file withtout PosenetDecoderOp (named posenet_middle.tflite)
2> Co-compile posenet_middle.tflite with model_x.tflite file -> output: posenet_middle_edgetpu.tflite and model_x_edgetpu.tflite file
3> Stick the PosenetDecoderOp back to posenet_middle_edgetpu.tflite (using  https://github.com/google-coral/edgetpu/blob/master/src/cpp/tools/join_tflite_models.cc)-> output: expected posenet_edgetpu.tflite (coccompiled)

is above flow correct?

**Comment by AlexTraan** [comment]
@mtyka : Can you help me?

**Comment by mtyka** [comment]
I uploaded version of the network without the decoder custom op.

**Comment by AlexTraan** [comment]
@mtyka Thank for your uploaded.

However, in order to stick the PosenetDecoderOp back to co-compiled model, i also need a *.tflite file that included only PosenetDecoderOp. Can you continue to help me?

**Comment by AlexTraan** [comment]
@mtyka 
Thank you for your helping so far.

But i still need a *.tflite file that included only PosenetDecoderOp, can you help me?

**Comment by mtyka** [comment]
Hi, sorry for the delay. I've uploaded the customop stub as a standalone model.

**Comment by AlexTraan** [comment]
@mtyka Hi, i got it. 
Thank you.

**Comment by AlexTraan** [comment]
@mtyka Hi,

I tried to co-compile, but when run:  ./join_tflite_models posenet_mobilenet_v1_075_481_641_quant_edgetpu.tflite customop_decoder_stub.tflite 

i faced crash with log: 
"WARNING: Logging before InitGoogleLogging() is written to STDERR
F0327 14:01:45.326503 18376 utils.cc:65] Check failed: ReadFile(file_path, file_content, &reporter) == kEdgeTpuApiOk (1 vs. 0) 
*** Check failure stack trace: ***
Aborted (core dumped)"

I found out below point:
+ The output type of posenet_mobilenet_v1_075_481_641_quant_edgetpu.tflite (already co-compiled) is uint8
+ The input type of customop_decoder_stub.tflite is float

I guess above point make failure. Can you help me?

**Comment by mtyka** [comment]
Hmm. This might not work for now unfortunately. I recommend for now just running the custom_op.tflite separately - it won't matter much since it runs on the CPU anyways.

**Comment by AlexTraan** [comment]
@mtyka i have tried custom_op.tflite using tflite_runtime Python but it failed to allocated tensor.
