### ISSUE TITLE
Update README to describe .tflite and edge TPU model generation steps

### ISSUE THREAD

**Issue by codingquark** [google-coral/project-posenet#2]
It would be great if README also showed how the quantized graph (tflite) was generated. 

This will also help people with their own custom trained models and with other versions of PoseNet (MobileNet 050, 100).

**Comment by mtyka** [comment]
In principle the quantized graph was created using quantization aware training (https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/contrib/quantize) but with respect to PoseNet specifically, unfortunately the training data and training scripts have not yet been released by the PoseNet team, so until they do so we're unable to offer these here for Coral either.
