### ISSUE TITLE
Multi-person detection issues

### ISSUE THREAD

**Issue by GOBish** [google-coral/project-posenet#21]
I've been having some issues when there are multiple people in the frame and the model connecting the people together, instead of recognizing the separate joints/pieces.
According to this article 
https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5
there is a separate posenet model (or algorithm it looks like) which works better when there are multiple people in the frame.
Is this pre-trained model (or algorithm) also available for the coral-optimized code?
Thanks!

**Comment by mtyka** [comment]
We're working on an update that will resolve some of these issues (will be part of next release).
