### ISSUE TITLE
gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

### ISSUE THREAD

**Issue by tomruarol** [google-coral/project-posenet#24]
I am trying to run `python3 pose_camera.py --h264` and I get the following error:

```
Loading model:  models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
Detected Edge TPU dev board.
Gstreamer pipeline:  v4l2src device=rtsp://administrator:@192.168.1.110/defaultPrimary?streamType=m ! video/x-h264,width=640,height=480,framerate=30/1 ! decodebin ! glupload ! glvideoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! freezer name=freezer ! glsvgoverlaysink name=overlaysink
               t. ! queue max-size-buffers=1 leaky=downstream ! glfilterbin filter=glbox name=glbox ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
            

(pose_camera.py:3988): Gdk-CRITICAL **: 11:18:22.098: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
```

**Note** I am getting the video source from a rtsp link from a camera and the Mendel version and Python API version I am using are:

- Python API Version ---> 2.13.0  ---> pip3 list

- Mendel Version --> 4.0 (Mendel Day) ---> cat /etc/mendel_version

**Comment by mtyka** [comment]
I've never tried it with rtsp:// before. GStreamer errors are notoriously useless, but somehow the pipeline can't be constructed.
It's possible the your source doesn't support the desired "video/x-h264,width=640,height=480,framerate=30/1 !" mode. You may have to query the source capabilities and figure out the correct mode.
Another idea: does the device have a monitor attached or x forwarding enabled ? If not, try changing the sink "autovideosink" to "fakesink" or plug in a monitor.

**Comment by tomruarol** [comment]
Attaching a monitor made no difference, the problem might be somewhere else. 
Whenever I go back to the project I will continue searching for a solution for this problem, but until then it will be paused.

**Comment by jpatokal** [comment]
I ran into the same issue, and simply running `export DISPLAY=:0` before running the program fixed the error for me.

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
