### ISSUE TITLE
Anyone trying to run this on windows?

### ISSUE THREAD

**Issue by marospekarik** [google-coral/project-posenet#25]
I'm curious if it works for windows. I'm having troubles installing gstreamer

**Comment by Nishanth2708** [comment]
I'm facing the same issue. Did your issue get resolved?

**Comment by Yash-Singh-Pathania** [comment]
same here i wonder if it can be resolved somehow

**Comment by hjonnala** [comment]
Hello,  as of now project-posenet has not been implemented on Windows yet.
