### ISSUE TITLE
GStreamer Segmentation Fault on Raspberry Pi 4

### ISSUE THREAD

**Issue by garyscetbon** [google-coral/project-posenet#26]
I ran install_requirements.sh but I'm getting this issue when running pose_camera.py on a Raspberry Pi 4 (using VNCViewer over ssh for remote display): 
```shell
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! videoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! freezer name=freezer ! rsvgoverlay name=overlay
                  ! videoconvert ! autovideosink
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,width=641,height=480 ! videobox name=box autocrop=true
                  ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
            
Segmentation fault
```
Any suggestion?

**Comment by mtyka** [comment]
Are you both using VNCViewer ? Could you try a local run ? Which version of the API are you using ?

**Comment by sviluppoh** [comment]
Yes, i'm using VNCViewer. The API version should be the latest. I've cloned this repo and installed all the dependencies

**Comment by sviluppoh** [comment]
tried to run with hdmi monitor.. it works. Thank you so much @mtyka

**Comment by mtyka** [comment]
Ok, sounds like it's an error todo with VNCViewer. I'm not sure what the fix is there, you may have to tweak the gstreamer pipeline's final sink to make it compatible. If you figure it out, let us know we can add a note for future users. Thanks !

**Comment by garyscetbon** [comment]
Made it work with VNCViewer by modifying the GStreamer pipeline: replace ```autovideosink``` with ```ximagesink``` in [gstreamer.py](https://github.com/google-coral/project-posenet/blob/da95b4f2724b13d981baa0fdd77cf87745a79f04/gstreamer.py#L353).

**Comment by Vetri213** [comment]
I am having a similar issue even when I am connected to a monitor. Please advise.

This is the output:


/home/mendel/Coral_Pose/project-posenet/gstreamer.py:15: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
/home/mendel/Coral_Pose/project-posenet/gstreamer.py:15: PyGIWarning: GstBase was imported without specifying a version first. Use gi.require_version('GstBase', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
/home/mendel/Coral_Pose/project-posenet/gstreamer.py:15: PyGIWarning: GstVideo was imported without specifying a version first. Use gi.require_version('GstVideo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
/home/mendel/Coral_Pose/project-posenet/gstreamer.py:15: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
Loading model:  models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! videoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! freezer name=freezer ! rsvgoverlay name=overlay
                  ! videoconvert ! autovideosink
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,width=641,height=480 ! videobox name=box autocrop=true
                  ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
