### ISSUE TITLE
let me ask you a question.

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [google-coral/project-posenet#28]
How many fps can coral dev board run?
I need realtime pose report but raspi is lower performance than my expected.
Thank you.

**Comment by mtyka** [comment]
It depends a lot on the resolution you want to use. You can get ~20-25 FPS at 720p on a RPI4+Einstein and on the devboard. More for lower resolutions. 
Often however the bottle neck is not the TPU but just moving the image buffers around. High FPS at high res requires using the GPU as well for processing.
