### ISSUE TITLE
Where can I collect the keypoints and do activity recognition?

### ISSUE THREAD

**Issue by YLTsai0609** [google-coral/project-posenet#29]
Hi.
I'm going to use this to do a human activity recognition project.
I want to collect the keypoints each frame into a numpy array.
After getting a sequence of keypoints.
I'll send it into a model to predict human action.

I want to know where can I do such a logic above?
It's seems that the streamming function just streamming out all of the frames in `gstreammer.py` line 159 `pipeline.set_state(Gst.State.PLAYING)`
Would someone like to give a hints or something? 
Tnanks!

**Comment by mtyka** [comment]
you can do that in either of the callbacks run_inference or render_overlay. 
For example here: https://github.com/google-coral/project-posenet/blob/435ac93204ec68783262865df7fa2185fd32b0bf/pose_camera.py#L136
If you need state you could change the simple callback function to a stateful class object that is callable.
