### ISSUE TITLE
OpenPose model to Posenet?

### ISSUE THREAD

**Issue by GOBish** [google-coral/project-posenet#30]
Hi,
Is there any way you could recommend to convert an openpose model to one for posenet? And then optimized for edge-tpu?
Thanks!

**Comment by zhangchenwei115** [comment]
Hi, I am also looking for Openpose model running on Google coral, did you get any idea?

**Comment by Namburger** [comment]
Are there extra features from openpose that isn't cover in the provided models?

**Comment by manoj7410** [comment]
Feel free to reopen if this feature is still requested.
