### ISSUE TITLE
Error running ResNet50 on Pi 4 with USB Accelerator

### ISSUE THREAD

**Issue by jingw222** [google-coral/project-posenet#31]
The model I'm currently testing is `posenet_resnet_50_640_480_16_quant_edgetpu_decoder.tflite`. 
 Loading the model with `PoseEngine` API seems to be just fine, but as soon as the model starts to run inferences, it aborts and throws me this error
```
F :842] transfer on tag 2 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
```
And that's not the case with the MobileNet version `posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite` at all. What gives?

Hardwares:
* Raspberry Pi 4
* Raspberry Pi Camera Module v2
* Coral USB Accelerator (connected to a USB 3 port on the Pi)
* Official USB-C power supply  (3A) 

Softwares:
* `python3-edgetpu`  v13.0
* `libedgetpu1-std:armhf`  v13.0

**Comment by mtyka** [comment]
These models are very large and push the limits of the USB connection - i've seen this issue before but I have no remedy. This is less of an issue with the DevBoard.
I see you are already using the USB3 port and a high quality cable, so i'm not sure what else to recommend.   I've definitely managed to run the 640x480x16 one on the Pi4 with the setup you describe. Maybe try one of the smaller resnet models ?

**Comment by jingw222** [comment]
It seems that way. 416x288x16 works, but the 640x480x16 one does not. How exactly did you manage to run 640x480x16 on the Pi4?

**Comment by mtyka** [comment]
Are you using libedgetpu1-std or libedgetpu1-max ?

**Comment by mtyka** [comment]
ok, I just tested this and confirmed my suspicion - the larger ResNet models will fail over USB if you use the slower libedgetpu1-std instead of libedgetpu1-max. I can exactly replicate your observations that with the throttled version the 640x480x16 ResNet fails but the smaller 416x288x16 one works. Reinstalling the faster libedgetpu1-max library restores the ability to run both. 
See here for more info in those two different library versions:
https://coral.ai/docs/accelerator/get-started/

**Comment by jingw222** [comment]
Thanks! Should have installed the overclocked libedgetpu1-max over the regular one. Now everything works again, and it speeds up inference on the mobilenet model ~30% in my case.

**Comment by Moehrenbaum** [comment]
@jingw222 James, it appears you are sucessfully running posenet on a raspi4 with the Coral usb TPU. would you mind sharing a github repo. I'm trying to get this to work here but so far fail. Thanks

**Comment by jingw222** [comment]
> @jingw222 James, it appears you are sucessfully running posenet on a raspi4 with the Coral usb TPU. would you mind sharing a github repo. I'm trying to get this to work here but so far fail. Thanks

Yep, for sure. Poke around [HIIT PI](https://github.com/jingw222/hiitpi) for whatever you're interested in. It's a web app deployed on the Pi in Docker containers though.
