### ISSUE TITLE
'PoseEngine' object has no attribute 'run_inference'

### ISSUE THREAD

**Issue by Chegde8** [google-coral/project-posenet#33]
I get the error:
`AttributeError: 'PoseEngine' object has no attribute 'run_inference'` when I run pose_camera.py. 
There doesn't seem to be an object named 'run_inference' in pose_engine.py. 
Could you please let me know if I'm missing something?

Thanks

**Comment by mtyka** [comment]
What's the version of the edgetpu library you are using ? 
It should be 
```
>>> print(edgetpu.__version__)
2.14.0
```

**Comment by Chegde8** [comment]
My edgetpu version is 2.11.1. 
This version has worked before though.

**Comment by mtyka** [comment]
Yes, I believe run_inference was renamed at some point from the older "RunInference".
The example was subsequently updated also and thus wont work with the older API anymore.
See: https://github.com/google-coral/project-posenet/commit/382082c1b22055e4fcc63ca2f1a6b0e4c7de5303#diff-21f97dd2896d97903b11cca987226babL125

While yo could rename it back, there have been other bugfixes related to PoseNet in the API as well so I strongly recommend moving to 2.14
