### ISSUE TITLE
gst-stream-error-quark: Internal data stream error on 1280x720

### ISSUE THREAD

**Issue by zlg9folira** [google-coral/project-posenet#35]
My camera source is 1920x1080 30fps. On raspberry Pi4 B+ aarch64, I have no problem running
`python3 pose_camera.py --res 480x360`
`python3 pose_camera.py --res 640x480`
They work seamlessly. However, I get error on:
 `python3 pose_camera.py --res 1280x720`

Output:
```
Loading model:  models/mobilenet/posenet_mobilenet_v1_075_721_1281_quant_decoder_edgetpu.tflite
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=1280,height=720,framerate=30/1 ! decodebin ! videoflip video-direction=identity ! tee name=t`
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! freezer name=freezer ! rsvgoverlay name=overlay
                  ! videoconvert ! autovideosink
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,width=1281,height=720 ! videobox name=box autocrop=true
                  ! video/x-raw,format=RGB,width=1281,height=721 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
Error: gst-stream-error-quark: Internal data stream error. (1): gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
```

Any idea?

**Comment by somewacko** [comment]
Ran into this, problem was that my camera didn't support 1280x720 using the raw codec @ 30/1 FPS (coral's gstreamer wrapper uses `30/1` everywhere). You can check `gst-device-monitor-1.0` to see your video devices and what they support.

For me, my camera supports 1280x720 @ 30/1 FPS with the h264 and jpeg codecs, so specifying `--h264` or `--jpeg` does the trick.

Changing the `framerate=30/1` lines in gstreamer.py also works if you need to use raw
