### ISSUE TITLE
pose output order

### ISSUE THREAD

**Issue by dariosortino** [google-coral/project-posenet#37]
Does anyone know which is the criterion of order for the output poses? To be clear, when I cycle for pose in poses, which is the first, the second one, etc with respect to the scene?

**Comment by mtyka** [comment]
The decoder will emit them roughly in order of confidence (key point
score).

Posenet has no ability to consistently identify or track individuals from
frame to frame, so the order is not particularly stable as individuals move.

-- sent from my phone
