### ISSUE TITLE
no output window

### ISSUE THREAD

**Issue by Ziegan** [google-coral/project-posenet#38]
while running the https://github.com/google-coral/project-posenet/blob/master/pose_camera.py on my newly setup coral dev board i can't see the output window & also it dosent show any errors

**Comment by jegamboafuentes** [comment]
Looking for the same answer

**Comment by Namburger** [comment]
II believe the pipeline for the devboard is somehow broken, for now one way to overcome this issue is to switch it to using the generic linux pipeline by changing [this line](https://github.com/google-coral/project-posenet/blob/master/gstreamer.py#L341) to:
```
if not detectCoralDevBoard():
```

**Comment by jegamboafuentes** [comment]
Awesome, that worked for me!

Thanks.

**Comment by Namburger** [comment]
no problems!

**Comment by Ziegan** [comment]
Yeah that worked for me also, thanks for sharing this info !

**Comment by Tylersuard** [comment]
I added that line of code to gstreamer.py, now the program won't run at all.  It quits while loading the model.
