### ISSUE TITLE
Gstreamer camera live streaming output is not diplayed...

### ISSUE THREAD

**Issue by smartkarthikn** [google-coral/project-posenet#39]
i have executed the pose_camera.py file but the output is not displayed and there is no errors too .. could u please help me with this ?
thank you ...

**Comment by Namburger** [comment]
Hey, here is a work around for now, but I'll look into what actually went wrong with the pipeline
https://github.com/google-coral/project-posenet/issues/38#issuecomment-710058891

**Comment by hjonnala** [comment]
@smartkarthikn are you still facing the issue..

**Comment by hjonnala** [comment]
Hope this issue was fixed. Feel free to reopen if issue still exists. Thanks!
