### ISSUE TITLE
How to get the output through the streaming server in edge TPU

### ISSUE THREAD

**Issue by wondersmiths** [google-coral/project-posenet#4]
Regarding the example file pose_camera.py, I would like to get some advice to get the video output using streaming server like the example here: https://coral.withgoogle.com/docs/dev-board/camera/#using-a-streaming-server. Not sure how to get this out.

**Comment by mtyka** [comment]
You mean you want to stream the results of PoseNet out like the quoted streaming example ? That feature isn't supported in tis pose net example out of the box, so you'd need to port over the streaming-relevant parts of the code from the streaming server example.
