### ISSUE TITLE
Can the included model be loaded by "Edge TPU runtime library" (on mac) and run with the USB Accelerator?

### ISSUE THREAD

**Issue by meteora9479** [google-coral/project-posenet#44]
Hi,

I download and unpack the Edge TPU runtime library on mac using:
<pre><code>
https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20201105.zip
</code></pre>

and I run the fallowing code (from coral detection example) to load the posenet model.

<pre><code>
import argparse
import time
import tensorflow.lite as tflite
import numpy as np

EDGETPU_SHARED_LIB = {
  'Linux': 'libedgetpu.so.1.0',
  'Darwin': 'libedgetpu.1.dylib',
  'Windows': 'edgetpu.dll'
}[platform.system()]

def make_interpreter(model_file):
  model_file, *device = model_file.split('@')
  return tflite.Interpreter(
      model_path=model_file,
      experimental_delegates=[
          tflite.experimental.load_delegate(EDGETPU_SHARED_LIB,
                               {'device': device[0]} if device else {})
      ])

model_path='models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite'
interpreter = make_interpreter(model_path)
interpreter.allocate_tensors()

</code></pre>

Then I get the error

<pre><code>
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-2d3d9ba033d0> in <module>
     11 labels = load_labels(labels_path) if labels_path else {}
     12 interpreter = make_interpreter(model_path)
---> 13 interpreter.allocate_tensors()

~/.pyenv/versions/3.8.6/envs/tf_2.3.0/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    241   def allocate_tensors(self):
    242     self._ensure_safe()
--> 243     return self._interpreter.AllocateTensors()
    244 
    245   def _safe_to_run(self):
RuntimeError: Encountered unresolved custom op: PosenetDecoderOp.Node number 1 (PosenetDecoderOp) failed to prepare.

</code></pre>

I ran example detection model and it worked well.
Have the latest library not supported  posenetDecoderOp yet?

**Comment by Namburger** [comment]
Hello, you'll need to register the posenet_decoder.so as I did [here](https://github.com/Namburger/project-posenet/blob/master/pose_engine.py#L76).
For now, please use my fork: https://github.com/Namburger/project-posenet
More details here:
https://github.com/google-coral/project-posenet/issues/42#issuecomment-738026058

**Comment by Namburger** [comment]
Although, as opposed to tflite, you'll need to use the tflite_runtime package we provided

**Comment by akosb** [comment]
@Namburger - the original question: Can the included model be loaded by "Edge TPU runtime library" **(on mac) and run with the USB Accelerator?**

The answer is **NO** according to [issue](https://github.com/google-coral/project-posenet/issues/71)
