### ISSUE TITLE
about API 2.11.1 upgrade

### ISSUE THREAD

**Issue by kmchinadragon** [google-coral/project-posenet#5]
As you may see, we can not upgrade Dev board just because we can not visit googl.com or similar web sites.  I try to copy the libedgetpu_arm64.so to /usr/lib/aarchxxxx  and use it under C++.  The demo says can not recognize DecompOP with version 1, which means the dev board still under version 1.0, but the lib is version 2.11.1 API,  how can we do to work around it by not using internet upgrading?
    thanks for any suggestion

**Comment by mtyka** [comment]
I dont think you'd be able to unfortunately :(
If you are able to obtain https://dl.google.com/coral/mendel/enterprise/mendel-enterprise-day-13.zip you can reflash you dev board with that and that comes with 2.11.1
