### ISSUE TITLE
Can't run simple_pose.py

### ISSUE THREAD

**Issue by XuTZ0912** [google-coral/project-posenet#50]
mendel@tuned-ibis:~/project-posenet$ python3 simple_pose.py

--2020-12-24 14:17:45--  https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hindu_marriage_ceremony_offering.jpg/640px-Hindu_marriage_ceremony_offering.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 103.102.166.240, 2001:df2:e500:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|103.102.166.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83328 (81K) [image/jpeg]
Saving to: ‘couple.jpg’

couple.jpg                      100%[======================================================>]  81.38K   509KB/s    in 0.2s

2020-12-24 14:17:46 (509 KB/s) - ‘couple.jpg’ saved [83328/83328]

Traceback (most recent call last):
  File "simple_pose.py", line 25, in <module>
    engine = PoseEngine('models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite')
  File "/home/mendel/project-posenet/pose_engine.py", line 85, in __init__
    BasicEngine.__init__(self, model_path)
  File "/home/mendel/.local/lib/python3.7/site-packages/edgetpu/basic/basic_engine.py", line 40, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 0 (edgetpu-custom-op) failed to prepare.
Failed to allocate tensors.

How to slove  this? Thanks all

**Comment by Namburger** [comment]
@XuTZ0912 Hello, please check out my pull request for the fix: https://github.com/google-coral/project-posenet/tree/ugrade-to-frogfish
