### ISSUE TITLE
Posenet decoder library for macos

### ISSUE THREAD

**Issue by nicoinch** [google-coral/project-posenet#56]
Hello,

Thank you for all the great examples you provide, a true gold mine !

I would like to use posenet on macos but I was not able due to posenet_decoder library. It seems it is not available on macos and I was not able to compile it.

Is there a way to make posenet work on macos ?

Thank you for your answer (and your time) !

**Comment by hjonnala** [comment]
Hi @nicoinch  please check this comment https://github.com/google-coral/project-bodypix/issues/22#issuecomment-940221257 to build posenet lib for macos.

Thanks
