### ISSUE TITLE
How to solve  ImportError: libedgetpu.so.?

### ISSUE THREAD

**Issue by pixellib** [google-coral/project-posenet#60]
ImportError: libedgetpu.so.1: cannot open shared object file: No such file or directory?

**Comment by Namburger** [comment]
Hello, which product are you using?
You need to go through our getting started page to see the proper step to set up your device.
In this case, it seems that the `libedgetpu-{std||max}` is missing

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
