### ISSUE TITLE
Startup with a Raspberry 4

### ISSUE THREAD

**Issue by Elmit2015** [google-coral/project-posenet#65]
I need some startup push ;-)

I use a RPi4 with 4 GB RAM.

_python3 shows:_
```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux

```
As I understand, I need to install first pycoral, tflite_runtime and libedgetpu.

_For pyCoral:_
`sudo apt-get install python3-pycoral
`
Also be sure you have the latest version of the Edge TPU runtime.
How do I check that?

_For tflite-runtime:_
```
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install python3-tflite-runtime

```
_For libedgetpu, please install the debian package:_
```
# None of this is needed on Coral boards
# This repo is needed for almost all packages below
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
# This repo is needed for only python3-coral-cloudiot and python3-coral-enviro
echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt-get update

sudo apt-get install libedgetpu1-max
sudo apt-get install python3-pycoral
sudo apt-get install python3-tflite-runtime
sudo apt-get install python3-coral-cloudiot
sudo apt-get install python3-coral-enviro
```

_and finally:_
`sh install_requirements.sh`

Is the sequence and the commands right?

**Comment by Elmit2015** [comment]
I tried above, but it failed. Please guide me on how to fix it:

I tested first:
vcgencmd version; vcgencmd get_throttled; vcgencmd measure_volts; vcgencmd measure_temp;vcgencmd measure_clock arm;
Jun  1 2020 13:24:51 
Copyright (c) 2012 Broadcom
version 6379679d1ec6a8c746d7e77e015f5b56b939976f (clean) (release) (start_x)
throttled=0x0
volt=0.8350V
temp=36.0'C
frequency(48)=600169920

unplug Coral

mkvirtualenv posenet
workon posenet

sudo apt-get install python3-pycoral
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libedgetpu1-std python3-tflite-runtime
The following packages will be REMOVED:
  edgetpu-examples python3-edgetpu
The following NEW packages will be installed:
  python3-pycoral python3-tflite-runtime
The following packages will be upgraded:
  libedgetpu1-std
1 upgraded, 2 newly installed, 2 to remove and 227 not upgraded.
Need to get 3,955 kB of archives.
After this operation, 32.5 MB disk space will be freed.
Do you want to continue? [Y/n]  Y
Get:1 https://packages.cloud.google.com/apt coral-edgetpu-stable/main armhf libedgetpu1-std armhf 15.0 [285 kB]
Get:2 https://packages.cloud.google.com/apt coral-edgetpu-stable/main armhf python3-tflite-runtime armhf 2.5.0 [2,929 kB]
Get:3 https://packages.cloud.google.com/apt coral-edgetpu-stable/main armhf python3-pycoral armhf 1.0 [741 kB]
Fetched 3,955 kB in 2s (2,213 kB/s)      
Reading changelogs... Done
(Reading database ... 139357 files and directories currently installed.)
Removing edgetpu-examples (14.0) ...
Removing python3-edgetpu (14.0) ...
(Reading database ... 139285 files and directories currently installed.)
Preparing to unpack .../libedgetpu1-std_15.0_armhf.deb ...
Unpacking libedgetpu1-std:armhf (15.0) over (14.0) ...
Selecting previously unselected package python3-tflite-runtime.
Preparing to unpack .../python3-tflite-runtime_2.5.0_armhf.deb ...
Unpacking python3-tflite-runtime (2.5.0) ...
Selecting previously unselected package python3-pycoral.
Preparing to unpack .../python3-pycoral_1.0_armhf.deb ...
Unpacking python3-pycoral (1.0) ...
Setting up python3-tflite-runtime (2.5.0) ...
Setting up libedgetpu1-std:armhf (15.0) ...
Setting up python3-pycoral (1.0) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...


echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install python3-tflite-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-tflite-runtime is already the newest version (2.5.0).
python3-tflite-runtime set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.


# None of this is needed on Coral boards
# This repo is needed for almost all packages below
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
# This repo is needed for only python3-coral-cloudiot and python3-coral-enviro
echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt-get update

sudo apt-get install libedgetpu1-std
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libedgetpu1-std is already the newest version (15.0).
0 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.

sudo apt-get install python3-pycoral
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  python3-pycoral
1 upgraded, 0 newly installed, 0 to remove and 249 not upgraded.
Need to get 742 kB of archives.
After this operation, 17.4 kB of additional disk space will be used.
Get:1 https://packages.cloud.google.com/apt coral-edgetpu-stable/main armhf python3-pycoral armhf 1.0.1 [742 kB]
Fetched 742 kB in 2s (388 kB/s)          
Reading changelogs... Done
(Reading database ... 139337 files and directories currently installed.)
Preparing to unpack .../python3-pycoral_1.0.1_armhf.deb ...
Unpacking python3-pycoral (1.0.1) over (1.0) ...
Setting up python3-pycoral (1.0.1) ...

sudo apt-get install python3-tflite-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-tflite-runtime is already the newest version (2.5.0).
0 upgraded, 0 newly installed, 0 to remove and 249 not upgraded.

sudo apt-get install python3-coral-cloudiot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-cryptoauthlib python3-paho-mqtt
The following NEW packages will be installed:
  python3-coral-cloudiot python3-cryptoauthlib python3-paho-mqtt
0 upgraded, 3 newly installed, 0 to remove and 249 not upgraded.
Need to get 114 kB of archives.
After this operation, 698 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.ossplanet.net/raspbian/raspbian buster/main armhf python3-paho-mqtt all 1.4.0-1 [44.9 kB]
Get:2 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-cryptoauthlib armhf 20190304-3 [62.3 kB]
Get:3 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-coral-cloudiot all 1.2 [6,816 B]
Fetched 114 kB in 12s (9,482 B/s)                                                                                                
Selecting previously unselected package python3-paho-mqtt.
(Reading database ... 139337 files and directories currently installed.)
Preparing to unpack .../python3-paho-mqtt_1.4.0-1_all.deb ...
Unpacking python3-paho-mqtt (1.4.0-1) ...
Selecting previously unselected package python3-cryptoauthlib.
Preparing to unpack .../python3-cryptoauthlib_20190304-3_armhf.deb ...
Unpacking python3-cryptoauthlib (20190304-3) ...
Selecting previously unselected package python3-coral-cloudiot.
Preparing to unpack .../python3-coral-cloudiot_1.2_all.deb ...
Unpacking python3-coral-cloudiot (1.2) ...
Setting up python3-paho-mqtt (1.4.0-1) ...
Setting up python3-cryptoauthlib (20190304-3) ...
Setting up python3-coral-cloudiot (1.2) ...

sudo apt-get install python3-coral-enviro
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  coral-enviro-drivers-dkms dkms python3-luma-core python3-luma-oled python3-periphery python3-smbus2 raspberrypi-kernel-headers
Suggested packages:
  python3-apport menu
The following NEW packages will be installed:
  coral-enviro-drivers-dkms dkms python3-coral-enviro python3-luma-core python3-luma-oled python3-periphery python3-smbus2
  raspberrypi-kernel-headers
0 upgraded, 8 newly installed, 0 to remove and 249 not upgraded.
Need to get 27.8 MB of archives.
After this operation, 181 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]
Get:2 http://mirror.ossplanet.net/raspbian/raspbian buster/main armhf dkms all 2.6.1-4 [74.4 kB]                
Get:3 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf coral-enviro-drivers-dkms all 1.5 [17.0 kB]
Get:4 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-smbus2 all 0.2.2-1 [8,456 B]
Get:5 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-luma-core all 1.8.3-1 [34.8 kB]
Get:6 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-luma-oled all 3.2.0-1 [13.8 kB]
Get:7 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-periphery all 1.1.1-1 [13.9 kB]
Get:8 https://packages.cloud.google.com/apt coral-cloud-stable/main armhf python3-coral-enviro all 1.1 [5,468 B]
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210303-1 [27.6 MB]            
Fetched 15.9 MB in 48min 52s (5,410 B/s)                                                                                         
Selecting previously unselected package dkms.
(Reading database ... 139388 files and directories currently installed.)
Preparing to unpack .../0-dkms_2.6.1-4_all.deb ...
Unpacking dkms (2.6.1-4) ...
Selecting previously unselected package raspberrypi-kernel-headers.
Preparing to unpack .../1-raspberrypi-kernel-headers_1.20210303-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1.20210303-1) ...
Selecting previously unselected package coral-enviro-drivers-dkms.
Preparing to unpack .../2-coral-enviro-drivers-dkms_1.5_all.deb ...
Unpacking coral-enviro-drivers-dkms (1.5) ...
Selecting previously unselected package python3-smbus2.
Preparing to unpack .../3-python3-smbus2_0.2.2-1_all.deb ...
Unpacking python3-smbus2 (0.2.2-1) ...
Selecting previously unselected package python3-luma-core.
Preparing to unpack .../4-python3-luma-core_1.8.3-1_all.deb ...
Unpacking python3-luma-core (1.8.3-1) ...
Selecting previously unselected package python3-luma-oled.
Preparing to unpack .../5-python3-luma-oled_3.2.0-1_all.deb ...
Unpacking python3-luma-oled (3.2.0-1) ...
Selecting previously unselected package python3-periphery.
Preparing to unpack .../6-python3-periphery_1.1.1-1_all.deb ...
Unpacking python3-periphery (1.1.1-1) ...
Selecting previously unselected package python3-coral-enviro.
Preparing to unpack .../7-python3-coral-enviro_1.1_all.deb ...
Unpacking python3-coral-enviro (1.1) ...
Setting up dkms (2.6.1-4) ...
Setting up raspberrypi-kernel-headers (1.20210303-1) ...
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v7+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v7l+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v8+
Setting up python3-periphery (1.1.1-1) ...
Setting up python3-smbus2 (0.2.2-1) ...
Setting up coral-enviro-drivers-dkms (1.5) ...
Loading new coral-enviro-drivers-1.5 DKMS files...
It is likely that 4.19.118-v7l+ belongs to a chroot's host
Building for 4.19.118+, 4.19.118-v7+, 4.19.118-v7l+, 4.19.118-v8+, 5.10.17+, 5.10.17-v7+ and 5.10.17-v7l+
Module build for kernel 4.19.118+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.17+
Error! Bad return status for module build on kernel: 5.10.17+ (armv7l)
Consult /var/lib/dkms/coral-enviro-drivers/1.5/build/make.log for more information.
dpkg: error processing package coral-enviro-drivers-dkms (--configure):
 installed coral-enviro-drivers-dkms package post-installation script subprocess returned error exit status 10
Setting up python3-luma-core (1.8.3-1) ...
Setting up python3-luma-oled (3.2.0-1) ...
dpkg: dependency problems prevent configuration of python3-coral-enviro:
 python3-coral-enviro depends on coral-enviro-drivers-dkms; however:
  Package coral-enviro-drivers-dkms is not configured yet.

dpkg: error processing package python3-coral-enviro (--configure):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 coral-enviro-drivers-dkms
 python3-coral-enviro
E: Sub-process /usr/bin/dpkg returned an error code (1)



cd ~/Projects/Joseph/project-posenet
sh install_requirements.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gobject-introspection is already the newest version (1.58.3-2).
gstreamer1.0-plugins-bad is already the newest version (1.14.4-1+b1).
python3-gi is already the newest version (3.30.4-1).
python3-gst-1.0 is already the newest version (1.14.4-1).
python3-numpy is already the newest version (1:1.16.2-1).
gir1.2-gtk-3.0 is already the newest version (3.24.5-1+rpt2).
gstreamer1.0-plugins-good is already the newest version (1.14.4-1+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 249 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up coral-enviro-drivers-dkms (1.5) ...
Removing old coral-enviro-drivers-1.5 DKMS files...

------------------------------
Deleting module version: 1.5
completely from the DKMS tree.
------------------------------
Done.
Loading new coral-enviro-drivers-1.5 DKMS files...
It is likely that 4.19.118-v7l+ belongs to a chroot's host
Building for 4.19.118+, 4.19.118-v7+, 4.19.118-v7l+, 4.19.118-v8+, 5.10.17+, 5.10.17-v7+ and 5.10.17-v7l+
Module build for kernel 4.19.118+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.17+
Error! Bad return status for module build on kernel: 5.10.17+ (armv7l)
Consult /var/lib/dkms/coral-enviro-drivers/1.5/build/make.log for more information.
dpkg: error processing package coral-enviro-drivers-dkms (--configure):
 installed coral-enviro-drivers-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of python3-coral-enviro:
 python3-coral-enviro depends on coral-enviro-drivers-dkms; however:
  Package coral-enviro-drivers-dkms is not configured yet.

dpkg: error processing package python3-coral-enviro (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 coral-enviro-drivers-dkms
 python3-coral-enviro
E: Sub-process /usr/bin/dpkg returned an error code (1)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: svgwrite in /home/pi/.virtualenvs/posenet/lib/python3.7/site-packages (1.4.1)
Installing Raspberry Pi specific dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-rpi.gpio rpi.gpio-common
The following packages will be upgraded:
  python-rpi.gpio python3-rpi.gpio rpi.gpio-common
3 upgraded, 0 newly installed, 0 to remove and 246 not upgraded.
2 not fully installed or removed.
Need to get 47.3 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf python-rpi.gpio armhf 0.7.0-0.1~bpo10+4 [20.7 kB]
Get:2 http://archive.raspberrypi.org/debian buster/main armhf python3-rpi.gpio armhf 0.7.0-0.1~bpo10+4 [20.7 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf rpi.gpio-common armhf 0.7.0-0.1~bpo10+4 [5,952 B]
Fetched 47.3 kB in 1s (44.6 kB/s)          
Reading changelogs... Done
(Reading database ... 194080 files and directories currently installed.)
Preparing to unpack .../python-rpi.gpio_0.7.0-0.1~bpo10+4_armhf.deb ...
Unpacking python-rpi.gpio (0.7.0-0.1~bpo10+4) over (0.7.0-0.1~bpo10+1) ...
Preparing to unpack .../python3-rpi.gpio_0.7.0-0.1~bpo10+4_armhf.deb ...
Unpacking python3-rpi.gpio (0.7.0-0.1~bpo10+4) over (0.7.0-0.1~bpo10+1) ...
Preparing to unpack .../rpi.gpio-common_0.7.0-0.1~bpo10+4_armhf.deb ...
Unpacking rpi.gpio-common:armhf (0.7.0-0.1~bpo10+4) over (0.7.0-0.1~bpo10+1) ...
Setting up coral-enviro-drivers-dkms (1.5) ...
Removing old coral-enviro-drivers-1.5 DKMS files...

------------------------------
Deleting module version: 1.5
completely from the DKMS tree.
------------------------------
Done.
Loading new coral-enviro-drivers-1.5 DKMS files...
It is likely that 4.19.118-v7l+ belongs to a chroot's host
Building for 4.19.118+, 4.19.118-v7+, 4.19.118-v7l+, 4.19.118-v8+, 5.10.17+, 5.10.17-v7+ and 5.10.17-v7l+
Module build for kernel 4.19.118+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.118-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.17+
Error! Bad return status for module build on kernel: 5.10.17+ (armv7l)
Consult /var/lib/dkms/coral-enviro-drivers/1.5/build/make.log for more information.
dpkg: error processing package coral-enviro-drivers-dkms (--configure):
 installed coral-enviro-drivers-dkms package post-installation script subprocess returned error exit status 10
Setting up rpi.gpio-common:armhf (0.7.0-0.1~bpo10+4) ...
Setting up python3-rpi.gpio (0.7.0-0.1~bpo10+4) ...
Setting up python-rpi.gpio (0.7.0-0.1~bpo10+4) ...
dpkg: dependency problems prevent configuration of python3-coral-enviro:
 python3-coral-enviro depends on coral-enviro-drivers-dkms; however:
  Package coral-enviro-drivers-dkms is not configured yet.

dpkg: error processing package python3-coral-enviro (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 coral-enviro-drivers-dkms
 python3-coral-enviro
E: Sub-process /usr/bin/dpkg returned an error code (1)


Errors as you can see. How to fix it?

**Comment by Elmit2015** [comment]
I followed the first error:

 cat /var/lib/dkms/coral-enviro-drivers/1.5/build/make.log 
DKMS make.log for coral-enviro-drivers-1.5 for kernel 5.10.17+ (armv7l)
Mon 29 Mar 2021 12:36:09 PM CST
make: Entering directory '/usr/src/linux-headers-5.10.17+'
  CC [M]  /var/lib/dkms/coral-enviro-drivers/1.5/build/light/opt3001.o
  CC [M]  /var/lib/dkms/coral-enviro-drivers/1.5/build/humidity/hdc20x0.o
  CC [M]  /var/lib/dkms/coral-enviro-drivers/1.5/build/adc/ti-ads1015.o
  CC [M]  /var/lib/dkms/coral-enviro-drivers/1.5/build/pressure/bmp280.o
/var/lib/dkms/coral-enviro-drivers/1.5/build/adc/ti-ads1015.c:797:16: error: ‘iio_triggered_buffer_postenable’ undeclared here (not in a function); did you mean ‘iio_triggered_buffer_cleanup’?
  .postenable = iio_triggered_buffer_postenable,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                iio_triggered_buffer_cleanup
/var/lib/dkms/coral-enviro-drivers/1.5/build/adc/ti-ads1015.c:798:16: error: ‘iio_triggered_buffer_predisable’ undeclared here (not in a function); did you mean ‘iio_triggered_buffer_cleanup’?
  .predisable = iio_triggered_buffer_predisable,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                iio_triggered_buffer_cleanup
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/coral-enviro-drivers/1.5/build/adc/ti-ads1015.o] Error 1
make[1]: *** [scripts/Makefile.build:496: /var/lib/dkms/coral-enviro-drivers/1.5/build/adc] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1804: /var/lib/dkms/coral-enviro-drivers/1.5/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.10.17+'

**Comment by Elmit2015** [comment]
Does anybody have a hint of what I am missing?

**Comment by el-tocino** [comment]
Getting a similar error trying to install python3-coral-enviro on a pi zero wh, running buster.  Apt update has been completed successfully, anything else I try works.  Device worked on an older version of raspbian, as well.

**Comment by scottamain** [comment]
@Elmit2015 I think you can ignore those errors because they're about the enviro-board, which you don't need for this project. None of the instructions mention running "sudo apt-get install python3-coral-enviro" so why did you do that? (It's definitely interesting that you have this error, but it's not related to this posenet project, so I'm curious how you arrived there.)

Regarding your very first question:
"Also be sure you have the latest version of the Edge TPU runtime.
How do I check that?"
As long as you have the latest version of each, you're all set. The instructions to install the runtime library are in the USB Accelerator setup guide: https://coral.ai/docs/accelerator/get-started#runtime-on-linux
(Also, `apt-get install python3-pycoral` will install the libedgetpu dependency.)

So with both the pycoral library and libedgetpu library installed, you should be all set. 

**Note:** If you tried one of the posenet scripts (such as pose_camera.py) on Raspberry Pi before June 18, then it would not have worked for a very different reason (maybe that was your actual problem but you didn't share that error message). But this project is now setup to support RPI out of the box, so try again.

**Comment by hjonnala** [comment]
Please try the [Get started with the USB Accelerator](https://coral.ai/docs/accelerator/get-started/) demo on Raspbeery pi 4 and feel free to reopen if issue still exists.
