### ISSUE TITLE
RuntimeError: Found builtin operator ADD with custom options.

### ISSUE THREAD

**Issue by smertrios** [google-coral/project-posenet#68]
Hi, I'm trying to run posenet on a custom ARMv7 + coral module but **allocate_tensors()** fails with:

> Traceback (most recent call last):
  File "/data/coral_posenet/pose_camera.py", line 186, in <module>
    main()
  File "/data/coral_posenet/pose_camera.py", line 128, in main
    model = PoseEngine('models/mobilenet/posenet_mobilenet_v1_075_353_481_quant_decoder_edgetpu.tflite')    
  File "/data/coral_posenet/pose_engine.py", line 96, in __init__
    self._interpreter.allocate_tensors() 
  File "/usr/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
**RuntimeError: Found builtin operator ADD with custom options.**
Found builtin operator ADD with custom options.
external/org_tensorflow/tensorflow/lite/kernels/add.cc:91 NumInputs(node) != 2 (0 != 2)Node number 0 (ADD) failed to prepare.

Using:
* tflite_runtime => 2.5
* libedgetpu.so.1 => armv7
* posenet_decoder.so => armv7a

**Comment by hjonnala** [comment]
Hi, Please provide the details to reproduce the issue.

**Comment by smertrios** [comment]
@hjonnala I eventually found the issue: the model was corrupted (actually truncated) due to a transport/copy error.

Somehow the interpreter doesn't seem to detect that the model is corrupted and the resulting reported error is confusing.
