### ISSUE TITLE
Run pose_camera.py in WSL2

### ISSUE THREAD

**Issue by jorgemmar10** [google-coral/project-posenet#72]
### Description

Hello,

I am using the CoralDevBoard with the coral camera on a Windows 10 computer; to view graphics and run GUI programs, I use vcxsrv. I am working with WSL2 (Windows Subsystem for Linux) and I have successfully installed all the requirements. I was able to run the simple_pose.py module, but I have not been able to run the pose_camera.py example. The output is attached.

I then ran the gstreamer.py file and got the same error of not being able to display.

Can I actually get a display through WSL2?   If not, is there a way to stream this through a sever, in the same way, that the demo for the coral camera set up does (https://coral.ai/docs/dev-board/camera/#view-with-a-streaming-server)?

I appreciate your help

<details><summary>Click to expand!</summary> 

### Issue Type

Support

### Operating System

Windows 10

### Coral Device

Dev Board, Coral Camera

### Programming Language

Python 3.7

### Relevant Log Output

```shell
(pose_camera.py:3975): dbind-WARNING **: 10:45:37.139: Could not open X display
Loading model:  models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! videoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! freezer name=freezer ! rsvgoverlay name=overlay
                  ! videoconvert ! autovideosink
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,width=641,height=480 ! videobox name=box autocrop=true
                  ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true

Gdk-Message: 10:45:40.116: Lost connection to Wayland compositor.
```

</details>

**Comment by hjonnala** [comment]
Hello @jorgemmar10 we haven't tested coral devices on WSL. Can you please tell us why you are using WSL as you can connect to the Dev Board through Windows itself.

**Comment by jorgemmar10** [comment]
> Hello @jorgemmar10 we haven't tested coral devices on WSL. Can you please tell us why you are using WSL as you can connect to the Dev Board through Windows itself.

Hello,
I used WSL for convenience purposes; I was able to get it to work using the instructions provided online. Thank you for your help.
