### ISSUE TITLE
Connection refused and import error relating to headless RPI

### ISSUE THREAD

**Issue by andrewtvuong** [google-coral/project-posenet#73]
### Description

I've followed all the install instructions successfully described under https://github.com/google-coral/project-posenet#examples-in-this-repo section. Included log.

<details><summary>Click to expand!</summary> 

### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.5

### Relevant Log Output

```shell
pi@posture:~/project-posenet $ python3 pose_camera.py --jpeg
/home/pi/project-posenet/gstreamer.py:14: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
/home/pi/project-posenet/gstreamer.py:14: PyGIWarning: GstBase was imported without specifying a version first. Use gi.require_version('GstBase', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
/home/pi/project-posenet/gstreamer.py:14: PyGIWarning: GstVideo was imported without specifying a version first. Use gi.require_version('GstVideo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
/home/pi/project-posenet/gstreamer.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gst, GstBase, GstVideo, Gtk
Traceback (most recent call last):
  File "pose_camera.py", line 26, in <module>
    from pose_engine import PoseEngine
  File "/home/pi/project-posenet/pose_engine.py", line 15, in <module>
    from pycoral.utils import edgetpu
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ImportError: No module named 'pycoral.pybind._pywrap_coral'
```
</details>

**Comment by hjonnala** [comment]
can you please check your pycoral version. If its not 2.0.0 please follow this link to install pycoral: https://coral.ai/software/#debian-packages

**Comment by andrewtvuong** [comment]
Yup it's 2.0.0 as output of pip3 list

**Comment by hjonnala** [comment]
can you past the output of this command : `ls /usr/lib/python3/dist-packages/pycoral/` to check pybind folder exist or not. If its not there please try uninstall install `python3-pycoral`

**Comment by andrewtvuong** [comment]
Hi @hjonnala thanks for your help it seems following the instructions on https://github.com/google-coral/project-posenet#examples-in-this-repo leads to installing two different pycoral on Raspberry OS. 

`sudo apt-get install python3-pycoral` from https://coral.ai/software#pycoral-api
`sudo apt-get install libedgetpu1-std` from https://coral.ai/docs/accelerator/get-started/#runtime-on-linux
`sh install_requirements.sh` from https://github.com/google-coral/project-posenet#examples-in-this-repo

Removing the pip3 installed version of pycoral corrected the issue.
