### ISSUE TITLE
Splitting model for multiple TPUs

### ISSUE THREAD

**Issue by anoop54** [google-coral/project-posenet#75]
### Description

Hi I want to split the model so I can run segments on multiple tpus so I can take advantage of the local cache. Is this possible? edgetpu_compiler --num_segments=4 model.tflite but I think this is only for models during compile time? As it does not do anything and just returns the version of the compiler. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Build/Install

### Operating System

Linux, Ubuntu

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
yes, you can split the model using `edgetpu_compiler -s  --num_segments=4 model.tflite `. It would give you 4 edgetpu.tflite models as output.

**Comment by hjonnala** [comment]
@anoop54 are you able to split the model?

**Comment by hjonnala** [comment]
Feel free top reopen if you have any questions. Thanks!

**Comment by anoop54** [comment]
> @anoop54 are you able to split the model?

No actually. I assumed that we are not able to split compiled models. Is this not the case?

**Comment by hjonnala** [comment]
Yes, we won't able to split the model that is already compiled for edgetpu. To split the models we need to pass an uncompiled tflite model.
