### ISSUE TITLE
Banana pose

### ISSUE THREAD

**Issue by vipelz** [google-coral/project-posenet#77]
### Description

For a small project with a tiny robotic arm I would like to do pose estimation with 3 or 4 bananas viewed with a webcam. 
 Is it possible to train with banana pictures?
 It would be in real time or how many fps do I get with Coral?
 Is it possible to show the main coordinates on the screen in real time?
 Thanks!!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Other Devices

Rapsberry Pi 4

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, @vipelz it is not possible to train with banana pictures with posenet_lib. Thanks!
