### ISSUE TITLE
Windows 10 Support?

### ISSUE THREAD

**Issue by RLux8** [google-coral/project-posenet#79]
Are there any plans to provide a Windows port of the posenet_decoder library (posenet_decoder.so) at some point? 

Are there options to run this posenet_decoder in python natively?

**Comment by hjonnala** [comment]
@RLux8 Unfortunately, we don't have any plans to support posenet_decoder library for windows in the near future.

**Comment by mpreach** [comment]
I would love to get a windows version, because I'm working with the M.2 Accelerator in a windows maschine... 

Did your plans changed ?
