### ISSUE TITLE
Probably naive question

### ISSUE THREAD

**Issue by neilyoung** [google-coral/project-posenet#89]
### Description

...Would it be possible to estimate the 6DOF pose of the camera from the pose detections of the Coral? I mean rotation and translation vectors.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @neilyoung we don't have any example models/demos to estimate  the 6DOF pose of the camera from the pose detections. It might be possible if it can be done with tflite models..

**Comment by neilyoung** [comment]
I'm unfortunately not the expert, but there is some buzz around "EfficientPose" (even though I couldn't get it running on an Nvidia fitted device). There are some forked project based on this https://github.com/ybkscht/EfficientPose

Not sure, it mentions Keras and no Tensorflow, so it might not fit

**Comment by hjonnala** [comment]
[keras](https://keras.io/about/) is high level API of Tensorflow2. It shouldn't be a problem. But I am not sure if [this model](https://github.com/ybkscht/EfficientPose) can be converted to int8 tflite and compatible with [EdgeTPU](https://coral.ai/docs/edgetpu/models-intro/#model-requirements).

**Comment by neilyoung** [comment]
Thanks, this is very helpful. Do you have some resources where to learn how to attempt such a conversion? I would also like to learn, how to retrain a 90 object model to "person" only, since this is the only "object" I'm interested in. I expect to see a boost in inference rate then.

**Comment by hjonnala** [comment]
Please check the [tutorials](https://github.com/google-coral/tutorials) examples and [tflite](https://www.tensorflow.org/lite/performance/post_training_quantization) documentation to convert the tensorflow models to tflite. Also check with the [tensorflow team](https://www.tensorflow.org/lite/tutorials/pose_classification) on how to reatrain a 90 object model. Thanks!
