### ISSUE TITLE
Question on Usability and Expansion of this repository

### ISSUE THREAD

**Issue by zain-altaf** [google-coral/project-posenet#90]
### Description

Hi 

I tried out this repo with the Google coral dev board mini and the coral camera and it works really nicely! I was just wondering how I could now go about using it in being able to train a custom model to use in a different setting? I'm quite new to all this computer vision stuff and I don't really know how to go about implementing this repository in custom real-time settings. 

Thanks! 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Mendel Linux, Linux

### Coral Device

Dev Board Mini

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @zain-altaf it's not possible to train a custom model using this repository. Instead you can  replace this [repo models](https://github.com/google-coral/project-posenet/blob/master/pose_camera.py#L103) with your custom posenet model([train the model, convert to tflite and compile with edgeptu compiler](https://coral.ai/docs/edgetpu/models-intro/)).

Please check with tensorflow team for any support for training models for pose estimation at: https://github.com/tensorflow/models.. Thanks!!
