### ISSUE TITLE
anonymizer.py help

### ISSUE THREAD

**Issue by zain-altaf** [google-coral/project-posenet#92]
### Description

Hi

In the READ.ME it says that by using anonymizer.py, you can safely store and analyze movements by making the movement detection anonymous. How does one go about taking the video footage being shot with a coral camera for example and store these movement patterns in an MP4 or MOV file that can be used to train a tflite model?

Thanks!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.5, Python 3.7, Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
closing due to the duplicate issue at: https://github.com/google-coral/project-posenet/issues/91
