### ISSUE TITLE
Core dumped with coral

### ISSUE THREAD

**Issue by JasseurHadded1** [google-coral/project-posenet#95]
### Description

Hello,

I have my own tflite model and I want to run it with Coral Usb accelerator, I did the quantization and I compile it with the edgetpu_compiler, when I load the model with interpreter and then I allocate tensors I get Segmentation fault, The tflite models (quantized  and not) works well, and I have tried coral with the classify_images example and it worked well.

Any explication or solution for that?

my tensorflow version is 2.12.0 and my tflite version is 2.11.0

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
closing due to the duplicate issue at:  https://github.com/google-coral/edgetpu/issues/712
